<<<<<<< HEAD
name: transformer
=======
name: transformer_torch
>>>>>>> 259dae85273075d92e9e6e37bfe69e54d198e61e
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - plotly
  - jupyter-dash
  - scikit-learn
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - pip
  - gensim
  - pip:
    - torch-summary